package rs.ac.uns.ftn.xws.ws.messageid;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
<<<<<<< HEAD:Banka/gen/rs/ac/uns/ftn/xws/ws/mpb/MpbDocumentService.java
 * 2015-05-24T20:21:16.869+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "MpbDocumentService", 
                  wsdlLocation = "file:/C:/Users/Bandjur/Desktop/Workspace/XWS-BSEP-PI/XWS/NiceHead/Banka/WEB-INF/wsdl/mpb.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/mpb") 
public class MpbDocumentService extends Service {
=======
 * 2015-05-20T12:30:07.443+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "MessageIdDocumentService", 
                  wsdlLocation = "file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/messageId.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/messageId") 
public class MessageIdDocumentService extends Service {
>>>>>>> 6f1009ea04cc725a27921b9af916ab32785a6187:CentralnaBanka/src/main/java/rs/ac/uns/ftn/xws/ws/messageid/MessageIdDocumentService.java

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/xws/ws/messageId", "MessageIdDocumentService");
    public final static QName MessageIdDocumentPort = new QName("http://www.ftn.uns.ac.rs/xws/ws/messageId", "MessageIdDocumentPort");
    static {
        URL url = null;
        try {
<<<<<<< HEAD:Banka/gen/rs/ac/uns/ftn/xws/ws/mpb/MpbDocumentService.java
            url = new URL("file:/C:/Users/Bandjur/Desktop/Workspace/XWS-BSEP-PI/XWS/NiceHead/Banka/WEB-INF/wsdl/mpb.wsdl");
=======
            url = new URL("file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/messageId.wsdl");
>>>>>>> 6f1009ea04cc725a27921b9af916ab32785a6187:CentralnaBanka/src/main/java/rs/ac/uns/ftn/xws/ws/messageid/MessageIdDocumentService.java
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MessageIdDocumentService.class.getName())
                .log(java.util.logging.Level.INFO, 
<<<<<<< HEAD:Banka/gen/rs/ac/uns/ftn/xws/ws/mpb/MpbDocumentService.java
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Bandjur/Desktop/Workspace/XWS-BSEP-PI/XWS/NiceHead/Banka/WEB-INF/wsdl/mpb.wsdl");
=======
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/messageId.wsdl");
>>>>>>> 6f1009ea04cc725a27921b9af916ab32785a6187:CentralnaBanka/src/main/java/rs/ac/uns/ftn/xws/ws/messageid/MessageIdDocumentService.java
        }
        WSDL_LOCATION = url;
    }

    public MessageIdDocumentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MessageIdDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageIdDocumentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessageIdDocumentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessageIdDocumentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessageIdDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MessageIdDocument
     */
    @WebEndpoint(name = "MessageIdDocumentPort")
    public MessageIdDocument getMessageIdDocumentPort() {
        return super.getPort(MessageIdDocumentPort, MessageIdDocument.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageIdDocument
     */
    @WebEndpoint(name = "MessageIdDocumentPort")
    public MessageIdDocument getMessageIdDocumentPort(WebServiceFeature... features) {
        return super.getPort(MessageIdDocumentPort, MessageIdDocument.class, features);
    }

}
