
package rs.ac.uns.ftn.xws.ws.messageid;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-20T12:30:07.438+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class MessageIdDocument_MessageIdDocumentPort_Server{

    protected MessageIdDocument_MessageIdDocumentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MessageIdDocumentImpl();
        String address = "http://localhost:8080/messageId";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new MessageIdDocument_MessageIdDocumentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
