package rs.ac.uns.ftn.xws.ws.mpcb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-19T15:57:34.887+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "MpcbDocumentService", 
                  wsdlLocation = "file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/mpcb.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/mpcb") 
public class MpcbDocumentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/xws/ws/mpcb", "MpcbDocumentService");
    public final static QName MpcbDocumentPort = new QName("http://www.ftn.uns.ac.rs/xws/ws/mpcb", "MpcbDocumentPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/mpcb.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MpcbDocumentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/mpcb.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MpcbDocumentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MpcbDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MpcbDocumentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MpcbDocumentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MpcbDocumentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MpcbDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MpcbDocument
     */
    @WebEndpoint(name = "MpcbDocumentPort")
    public MpcbDocument getMpcbDocumentPort() {
        return super.getPort(MpcbDocumentPort, MpcbDocument.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MpcbDocument
     */
    @WebEndpoint(name = "MpcbDocumentPort")
    public MpcbDocument getMpcbDocumentPort(WebServiceFeature... features) {
        return super.getPort(MpcbDocumentPort, MpcbDocument.class, features);
    }

}
