
package rs.ac.uns.ftn.xws.ws.mpcb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;

import rs.ac.uns.ftn.xws.generated.Mt102;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-19T11:46:58.812+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class MpcbDocument_MpcbDocumentPort_Client {

    private MpcbDocument_MpcbDocumentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
    	try {
			URL wsdl = new URL(
					"http://localhost:8080/cb/services/MpcbDocument?wsdl");

			QName serviceName = new QName(
					"http://www.ftn.uns.ac.rs/xws/ws/mpcb",
					"MpcbDocumentService");
			QName portName = new QName(
					"http://www.ftn.uns.ac.rs/xws/ws/mpcb",
					"MpcbDocumentPort");

			Service service = Service.create(wsdl, serviceName);

			MpcbDocument mpcbService = service.getPort(portName,
					MpcbDocument.class);

			mpcbService.rtgsRequest(new Mt102());
		} catch (MalformedURLException e) {
			e.printStackTrace();
		} catch (MpException e) {
			System.out.println("exception");
		}
    }

}
