
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.ws.cb;

import java.util.logging.Logger;

import javax.ejb.Stateless;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-15T17:45:26.896+02:00
 * Generated source version: 2.6.5
 * 
 */

@Stateless
@javax.jws.WebService(
                      serviceName = "CbDocumentService",
                      portName = "CbDocumentPort",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/cb",
                      wsdlLocation = "file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/cb.wsdl",
                      endpointInterface = "rs.ac.uns.ftn.xws.ws.cb.CbDocument")
                      
public class CbDocumentImpl implements CbDocument {

    private static final Logger LOG = Logger.getLogger(CbDocumentImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.ws.cb.CbDocument#handleMt102(rs.ac.uns.ftn.xws.generated.Mt102  mt102 )*
     */
    public rs.ac.uns.ftn.xws.generated.Mt900 handleMt102(rs.ac.uns.ftn.xws.generated.Mt102 mt102) { 
        LOG.info("Executing operation handleMt102");
        System.out.println(mt102);
        try {
            rs.ac.uns.ftn.xws.generated.Mt900 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.ws.cb.CbDocument#handleMt103(rs.ac.uns.ftn.xws.generated.Mt103  mt103 )*
     */
    public rs.ac.uns.ftn.xws.generated.Mt900 handleMt103(rs.ac.uns.ftn.xws.generated.Mt103 mt103) { 
        LOG.info("Executing operation handleMt103");
        System.out.println(mt103);
        try {
            rs.ac.uns.ftn.xws.generated.Mt900 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
