package rs.ac.uns.ftn.xws.ws.cb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-15T17:45:26.947+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "CbDocumentService", 
                  wsdlLocation = "file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/cb.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/cb") 
public class CbDocumentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/xws/ws/cb", "CbDocumentService");
    public final static QName CbDocumentPort = new QName("http://www.ftn.uns.ac.rs/xws/ws/cb", "CbDocumentPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/cb.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CbDocumentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nikola42/Documents/Fakultet/XWS/projekat/NiceHead/CentralnaBanka/WEB-INF/wsdl/cb.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CbDocumentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CbDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CbDocumentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CbDocumentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CbDocumentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CbDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CbDocument
     */
    @WebEndpoint(name = "CbDocumentPort")
    public CbDocument getCbDocumentPort() {
        return super.getPort(CbDocumentPort, CbDocument.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CbDocument
     */
    @WebEndpoint(name = "CbDocumentPort")
    public CbDocument getCbDocumentPort(WebServiceFeature... features) {
        return super.getPort(CbDocumentPort, CbDocument.class, features);
    }

}
