package rs.ac.uns.ftn.xws.ws.cb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-15T17:45:26.915+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/cb", name = "CbDocument")
@XmlSeeAlso({rs.ac.uns.ftn.xws.generated.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CbDocument {

    @WebMethod
    @WebResult(name = "mt900", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mt900", partName = "mt900")
    public rs.ac.uns.ftn.xws.generated.Mt900 handleMt102(
        @WebParam(partName = "mt102", name = "mt102", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mt102")
        rs.ac.uns.ftn.xws.generated.Mt102 mt102
    );

    @WebMethod
    @WebResult(name = "mt900", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mt900", partName = "mt900")
    public rs.ac.uns.ftn.xws.generated.Mt900 handleMt103(
        @WebParam(partName = "mt103", name = "mt103", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mt103")
        rs.ac.uns.ftn.xws.generated.Mt103 mt103
    );
}
