package rs.ac.uns.ftn.xws.ws.cb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;

import rs.ac.uns.ftn.xws.generated.Mt102;

/**
 * This class was generated by Apache CXF 2.6.5 2015-05-13T23:21:44.986+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CbDocument_CbDocumentPort_Client {

	public static void main(String[] args) throws MalformedURLException {
		URL wsdl = new URL(
				"http://localhost:8080/cb/services/CbDocument?wsdl");

		QName serviceName = new QName("http://www.ftn.uns.ac.rs/xws/ws/cb",
				"CbDocumentService");
		QName portName = new QName("http://www.ftn.uns.ac.rs/xws/ws/cb",
				"CbDocumentPort");

		Service service = Service.create(wsdl, serviceName);

		CbDocument cbd = service.getPort(portName, CbDocument.class);

		System.out.println("cb call");
		cbd.handleMt102(new Mt102());
	}
}
