
package rs.ac.uns.ftn.xws.ws.po;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-29T14:27:42.438+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class PoDocument_PoDocumentPort_Server{

    protected PoDocument_PoDocumentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PoDocumentImpl();
        String address = "http://localhost:8080/po";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new PoDocument_PoDocumentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
