//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 08:26:22 PM CEST 
//

@XmlSchema(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/bsb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@javax.xml.bind.annotation.XmlNs(prefix = "bsb", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/bsb"),
		@javax.xml.bind.annotation.XmlNs(prefix = "cmn", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/cmn")
		})
//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.ac.uns.ftn.xws.domain;
import javax.xml.bind.annotation.XmlSchema;

