
package rs.ac.uns.ftn.xws.ws.swiftcode;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-19T10:12:54.849+02:00
 * Generated source version: 2.6.5
 */

@WebFault(name = "noBankAccountException", targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/swiftCode")
public class NoBankAccountException extends Exception {
    
    private java.lang.String noBankAccountException;

    public NoBankAccountException() {
        super();
    }
    
    public NoBankAccountException(String message) {
        super(message);
    }
    
    public NoBankAccountException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoBankAccountException(String message, java.lang.String noBankAccountException) {
        super(message);
        this.noBankAccountException = noBankAccountException;
    }

    public NoBankAccountException(String message, java.lang.String noBankAccountException, Throwable cause) {
        super(message, cause);
        this.noBankAccountException = noBankAccountException;
    }

    public java.lang.String getFaultInfo() {
        return this.noBankAccountException;
    }
}
