package rs.ac.uns.ftn.xws.ws.swiftcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-16T22:10:49.180+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/swiftCode", name = "SwiftCodeDocument")
@XmlSeeAlso({rs.ac.uns.ftn.xws.generated.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SwiftCodeDocument {

    @WebMethod
    @WebResult(name = "swiftCode", targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/swiftCode", partName = "swiftCode")
    public java.lang.String getSwiftCode(
        @WebParam(partName = "bankClearingAccountNumber", name = "bankClearingAccountNumber", targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/swiftCode")
        java.lang.String bankClearingAccountNumber
    );
}
