package rs.ac.uns.ftn.xws.ws.client.mpcb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-25T18:46:52.416+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/mpcb", name = "MpcbDocument")
@XmlSeeAlso({rs.ac.uns.ftn.xws.generated.mp.ObjectFactory.class, rs.ac.uns.ftn.xws.generated.cmn.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MpcbDocument {

    @WebMethod
    @WebResult(name = "mt900", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mp", partName = "rtgsDebitPart")
    public rs.ac.uns.ftn.xws.generated.mp.Mt900 rtgsRequest(
        @WebParam(partName = "rtgsRequestPart", name = "mt103", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mp")
        rs.ac.uns.ftn.xws.generated.mp.Mt103 rtgsRequestPart
    ) throws MpException;

    @WebMethod
    public void clearingRequest(
        @WebParam(partName = "clearingRequestPart", name = "mt102", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mp")
        rs.ac.uns.ftn.xws.generated.mp.Mt102 clearingRequestPart
    ) throws MpException;
}
