package rs.ac.uns.ftn.xws.ws.crl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-28T18:09:15.617+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/crl", name = "CrlDocument")
@XmlSeeAlso({rs.ac.uns.ftn.xws.generated.crl.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CrlDocument {

    @WebResult(name = "isRevoked", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/crl", partName = "isRevoked")
    @WebMethod
    public boolean isInCrl(
        @WebParam(partName = "certSerial", name = "certSerial", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/crl")
        java.lang.String certSerial
    );
}
