
package rs.ac.uns.ftn.xws.ws.crl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-28T18:09:15.539+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CrlDocument_CrlDocumentPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/xws/ws/crl", "CrlDocumentService");

    private CrlDocument_CrlDocumentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CrlDocumentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CrlDocumentService ss = new CrlDocumentService(wsdlURL, SERVICE_NAME);
        CrlDocument port = ss.getCrlDocumentPort();  
        
        {
        System.out.println("Invoking isInCrl...");
        java.lang.String _isInCrl_certSerial = "";
        boolean _isInCrl__return = port.isInCrl(_isInCrl_certSerial);
        System.out.println("isInCrl.result=" + _isInCrl__return);


        }

        System.exit(0);
    }

}
