
package rs.ac.uns.ftn.xws.ws.bankdetails;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-29T17:48:50.944+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class BdDocument_BdDocumentPort_Server{

    protected BdDocument_BdDocumentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BdDocumentImpl();
        String address = "http://localhost:8080/bankDetails";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new BdDocument_BdDocumentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
