
package rs.ac.uns.ftn.xws.ws.bsws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-24T20:21:22.814+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class BsDocument_BsDocumentPort_Server{

    protected BsDocument_BsDocumentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BsDocumentImpl();
        String address = "http://localhost:8080/bs";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new BsDocument_BsDocumentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
