package rs.ac.uns.ftn.xws.ws.bsws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-24T20:21:22.798+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/bsws", name = "BsDocument")
@XmlSeeAlso({rs.ac.uns.ftn.xws.generated.cmn.ObjectFactory.class, rs.ac.uns.ftn.xws.generated.bs.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BsDocument {

    @WebResult(name = "statement", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/bs", partName = "bsResponsePart")
    @WebMethod
    public rs.ac.uns.ftn.xws.generated.bs.Statement getStatement(
        @WebParam(partName = "bsRequestPart", name = "statementRequest", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/bs")
        rs.ac.uns.ftn.xws.generated.bs.StatementRequest bsRequestPart
    );
}
