/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.ws.bsws;

import java.util.List;
import java.util.logging.Logger;

import javax.ejb.Stateless;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import rs.ac.uns.ftn.xws.dao.PaymentDataDao;
import rs.ac.uns.ftn.xws.dao.util.ParserUtil;
import rs.ac.uns.ftn.xws.generated.bs.Statement;
import rs.ac.uns.ftn.xws.generated.cmn.Payment;

/**
 * This class was generated by Apache CXF 2.6.5 2015-05-24T20:21:22.783+02:00
 * Generated source version: 2.6.5
 * 
 */
@Stateless
@javax.jws.WebService(serviceName = "BsDocumentService", portName = "BsDocumentPort", targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/bsws", wsdlLocation = "file:/C:/Users/Bandjur/Desktop/Workspace/XWS-BSEP-PI/XWS/NiceHead/Banka/WEB-INF/wsdl/bs.wsdl", endpointInterface = "rs.ac.uns.ftn.xws.ws.bsws.BsDocument")
public class BsDocumentImpl implements BsDocument {

	private static final Logger LOG = Logger.getLogger(BsDocumentImpl.class
			.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * rs.ac.uns.ftn.xws.ws.bsws.BsDocument#getStatement(rs.ac.uns.ftn.xws.generated
	 * .bs.StatementRequest bsRequestPart )*
	 */
	public rs.ac.uns.ftn.xws.generated.bs.Statement getStatement(
			rs.ac.uns.ftn.xws.generated.bs.StatementRequest bsRequestPart) {
		LOG.info("Executing operation getStatement");
		LOG.info("Account number iz requesta = "
				+ bsRequestPart.getAccountNumber());
		Statement retVal = null;

		// Calendar calendar = bsRequestPart.getDate().toGregorianCalendar();
		// SimpleDateFormat formatter = new
		// SimpleDateFormat("MM/dd/yyyy hh:mm");
		// formatter.setTimeZone(calendar.getTimeZone());
		// String dateString = formatter.format(calendar.getTime());

		String dateString = "2015-05-21";
		//
		// String input = OrdersDataDao.getOrders(dateString,
		// bsRequestPart.getAccountNumber(),
		// bsRequestPart.getSectionalNumber());
		// List<Order> orders = ParserUtil.transformStringsIntoJAXB(input);
		
		System.out.println("SHOOOOOW-BRE");
		LOG.info("SHOOOOOW-BRE");
		
		
		List<Payment> payments = ParserUtil
				.transformStringsIntoJAXB(PaymentDataDao.getPayments(
						dateString, bsRequestPart.getAccountNumber(),
						bsRequestPart.getStatementNumber()));
		// retVal = new SectionalData();
		// set fields and return retVal
		
		if(payments.get(0).getCreditor()!=null) {
			System.out.println("TO JE TO !");
			LOG.info("TO JE TO");
		}

		LOG.info("SHOOOOOW");
		return retVal;
	}

}
