
package rs.ac.uns.ftn.xws.ws.bsws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import rs.ac.uns.ftn.xws.dao.util.DateUtil;
import rs.ac.uns.ftn.xws.ws.mpb.MpbDocument;
import rs.ac.uns.ftn.xws.ws.mpb.MpbDocumentService;
import rs.ac.uns.ftn.xws.xsd.bstatementrequest.BankStatmentRequest;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-20T01:00:08.583+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class BsDocument_BsDocumentPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/xws/ws/bsws", "BsDocumentService");

    private BsDocument_BsDocumentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BsDocumentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BsDocumentService ss = new BsDocumentService(wsdlURL, SERVICE_NAME);
        BsDocument port = ss.getBsDocumentPort();  
        
        {
        System.out.println("Invoking getSectionalData...");
        rs.ac.uns.ftn.xws.xsd.bstatementrequest.BankStatmentRequest _getSectionalData_bsRequestPart = null;
        
        _getSectionalData_bsRequestPart = new BankStatmentRequest();
        
        GregorianCalendar c = new GregorianCalendar();
        c.setTime(new Date());
        XMLGregorianCalendar gregoryDate = DatatypeFactory.newInstance().newXMLGregorianCalendar(c);
        
        _getSectionalData_bsRequestPart.setAccountNumber("310-0000000000011-83");
        _getSectionalData_bsRequestPart.setSectionalNumber(2);
        _getSectionalData_bsRequestPart.setDate(gregoryDate);
        
        port.getSectionalData(_getSectionalData_bsRequestPart);

        }
        System.exit(0);
    }

}
