//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 01:26:36 PM CEST 
//


package rs.ac.uns.ftn.xws.domain.mpb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mt102Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mt102Data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mt102Ref" type="{http://www.ftn.uns.ac.rs/xws/xsd/mpb}Mt102Ref" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mt102Data", propOrder = {
    "mt102Ref"
})
public class Mt102Data {

    protected List<Mt102Ref> mt102Ref;

    /**
     * Gets the value of the mt102Ref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mt102Ref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMt102Ref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mt102Ref }
     * 
     * 
     */
    public List<Mt102Ref> getMt102Ref() {
        if (mt102Ref == null) {
            mt102Ref = new ArrayList<Mt102Ref>();
        }
        return this.mt102Ref;
    }

}
