//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.28 at 05:59:44 PM CEST 
//


package rs.ac.uns.ftn.xws.domain.mpb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xws.domain.mpb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClearingData_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/xsd/mpb", "clearingData");
    private final static QName _CompanyData_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/xsd/mpb", "companyData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xws.domain.mpb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClearingData }
     * 
     */
    public ClearingData createClearingData() {
        return new ClearingData();
    }

    /**
     * Create an instance of {@link CompanyData }
     * 
     */
    public CompanyData createCompanyData() {
        return new CompanyData();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearingData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/mpb", name = "clearingData")
    public JAXBElement<ClearingData> createClearingData(ClearingData value) {
        return new JAXBElement<ClearingData>(_ClearingData_QNAME, ClearingData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompanyData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/mpb", name = "companyData")
    public JAXBElement<CompanyData> createCompanyData(CompanyData value) {
        return new JAXBElement<CompanyData>(_CompanyData_QNAME, CompanyData.class, null, value);
    }

}
