//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.28 at 05:59:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/mpb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@javax.xml.bind.annotation.XmlNs(prefix = "cmn", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/cmn"),
		@javax.xml.bind.annotation.XmlNs(prefix = "mpb", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/mpb"),
		@javax.xml.bind.annotation.XmlNs(prefix = "mp", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/mp") })
package rs.ac.uns.ftn.xws.domain.mpb;
