//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.29 at 12:26:33 AM CEST 
//


package rs.ac.uns.ftn.xmlbsep.domain.tokens;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xws.domain.tokens package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TokenList_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/xsd/tokens", "tokenList");
    private final static QName _Token_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/xsd/tokens", "token");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xws.domain.tokens
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TokenList }
     * 
     */
    public TokenList createTokenList() {
        return new TokenList();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link TokenList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/tokens", name = "tokenList")
    public JAXBElement<TokenList> createTokenList(TokenList value) {
        return new JAXBElement<TokenList>(_TokenList_QNAME, TokenList.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/tokens", name = "token")
    public JAXBElement<String> createToken(String value) {
        return new JAXBElement<String>(_Token_QNAME, String.class, null, value);
    }

}
