//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.16 at 01:41:26 AM CEST 
//


package rs.ac.uns.ftn.xws.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xws.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Bank_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/xsd/cb", "bank");
    private final static QName _BanksData_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/xsd/cb", "banksData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xws.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BanksData }
     * 
     */
    public BanksData createBanksData() {
        return new BanksData();
    }

    /**
     * Create an instance of {@link Bank }
     * 
     */
    public Bank createBank() {
        return new Bank();
    }

    /**
     * Create an instance of {@link BanksData.Banks }
     * 
     */
    public BanksData.Banks createBanksDataBanks() {
        return new BanksData.Banks();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bank }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/cb", name = "bank")
    public JAXBElement<Bank> createBank(Bank value) {
        return new JAXBElement<Bank>(_Bank_QNAME, Bank.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BanksData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/cb", name = "banksData")
    public JAXBElement<BanksData> createBanksData(BanksData value) {
        return new JAXBElement<BanksData>(_BanksData_QNAME, BanksData.class, null, value);
    }

}
