//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 05:41:31 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/cb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@javax.xml.bind.annotation.XmlNs(prefix = "mp", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/mp"),
		@javax.xml.bind.annotation.XmlNs(prefix = "cmn", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/common"),
		@javax.xml.bind.annotation.XmlNs(prefix = "cb", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/cb") })
package rs.ac.uns.ftn.xws.domain;

