
package rs.ac.uns.ftn.xws.ws.crl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-28T18:09:15.633+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class CrlDocument_CrlDocumentPort_Server{

    protected CrlDocument_CrlDocumentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CrlDocumentImpl();
        String address = "http://localhost:8080/crl";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CrlDocument_CrlDocumentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
