
package rs.ac.uns.ftn.xws.ws.crl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-28T18:09:15.539+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CrlDocument_CrlDocumentPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/xws/ws/crl", "CrlDocumentService");

    private CrlDocument_CrlDocumentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
    	try {
			URL wsdl = new URL(
					"http://localhost:8080/cb/services/CrlDocument?wsdl");

			QName serviceName = new QName(
					"http://www.ftn.uns.ac.rs/xws/ws/crl",
					"CrlDocumentService");
			QName portName = new QName(
					"http://www.ftn.uns.ac.rs/xws/ws/crl",
					"CrlDocumentPort");

			Service service = Service.create(wsdl, serviceName);

			CrlDocument crlService = service.getPort(portName,
					CrlDocument.class);

			System.out.println(crlService.isInCrl("1"));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
    }

}
