package rs.ac.uns.ftn.xws.ws.mpb;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-15T17:45:33.213+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/mpb", name = "MpbDocument")
@XmlSeeAlso({rs.ac.uns.ftn.xws.generated.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MpbDocument {

    @WebMethod
    @Oneway
    public void rtgsConfirm(
        @WebParam(partName = "rtgsConfirmPart", name = "rtgsConfirmMessage", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mpb")
        rs.ac.uns.ftn.xws.generated.RtgsConfirmMessage rtgsConfirmPart
    );

    @WebMethod
    @Oneway
    public void clearingConfirm(
        @WebParam(partName = "clearingConfirmPart", name = "clearingConfirmMessage", targetNamespace = "http://www.ftn.uns.ac.rs/xws/xsd/mpb")
        rs.ac.uns.ftn.xws.generated.ClearingConfirmMessage clearingConfirmPart
    );
}
