
package rs.ac.uns.ftn.xws.ws.mpb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;

import rs.ac.uns.ftn.xws.generated.ClearingConfirmMessage;
import rs.ac.uns.ftn.xws.generated.Mt102;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-13T23:21:50.181+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class MpbDocument_MpbDocumentPort_Client {

	public static void foo(Mt102 mt102) {
		try {
			URL wsdl = new URL(
					"http://localhost:8080/vezbe-wsdl-ws/services/MpbDocument?wsdl");

			QName serviceName = new QName("http://www.ftn.uns.ac.rs/xws/ws/mpb",
					"MpbDocumentService");
			QName portName = new QName("http://www.ftn.uns.ac.rs/xws/ws/mpb",
					"MpbDocumentPort");

			Service service = Service.create(wsdl, serviceName);

			MpbDocument mpbService = service.getPort(portName, MpbDocument.class);

			System.out.println("mpb call");
			mpbService.clearingConfirm(new ClearingConfirmMessage());
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}

}
