
package rs.ac.uns.ftn.xws.ws.cb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-13T18:48:00.237+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CbWsDocument_CbWsDocumentPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/xws/ws/cb", "CbWsDocumentService");

    private CbWsDocument_CbWsDocumentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CbWsDocumentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CbWsDocumentService ss = new CbWsDocumentService(wsdlURL, SERVICE_NAME);
        CbWsDocument port = ss.getCbWsDocumentPort();  
        
        {
        System.out.println("Invoking handleMt102...");
        rs.ac.uns.ftn.xws.bo.mt102.Mt102 _handleMt102_mt102 = null;
        rs.ac.uns.ftn.xws.bo.mt900.Mt900 _handleMt102__return = port.handleMt102(_handleMt102_mt102);
        System.out.println("handleMt102.result=" + _handleMt102__return);


        }
        {
        System.out.println("Invoking handleMt103...");
        rs.ac.uns.ftn.xws.bo.mt103.Mt103 _handleMt103_mt103 = null;
        rs.ac.uns.ftn.xws.bo.mt900.Mt900 _handleMt103__return = port.handleMt103(_handleMt103_mt103);
        System.out.println("handleMt103.result=" + _handleMt103__return);


        }

        System.exit(0);
    }

}
