
package rs.ac.uns.ftn.xws.ws.cb;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-13T18:48:00.434+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class CbWsDocument_CbWsDocumentPort_Server{

    protected CbWsDocument_CbWsDocumentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CbWsDocumentImpl();
        String address = "http://localhost:8080/cb";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CbWsDocument_CbWsDocumentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
