package rs.ac.uns.ftn.xws.ws.cb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-13T18:48:00.423+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/ws/cb", name = "CbWsDocument")
@XmlSeeAlso({rs.ac.uns.ftn.xws.bo.mt103.ObjectFactory.class, rs.ac.uns.ftn.xws.bo.mt102.ObjectFactory.class, rs.ac.uns.ftn.xws.bo.mp.ObjectFactory.class, rs.ac.uns.ftn.xws.bo.mt900.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CbWsDocument {

    @WebMethod
    @WebResult(name = "mt900", targetNamespace = "http://www.ftn.uns.ac.rs/xws/bo/mt900", partName = "mt900")
    public rs.ac.uns.ftn.xws.bo.mt900.Mt900 handleMt102(
        @WebParam(partName = "mt102", name = "mt102", targetNamespace = "http://www.ftn.uns.ac.rs/xws/bo/mt102")
        rs.ac.uns.ftn.xws.bo.mt102.Mt102 mt102
    );

    @WebMethod
    @WebResult(name = "mt900", targetNamespace = "http://www.ftn.uns.ac.rs/xws/bo/mt900", partName = "mt900")
    public rs.ac.uns.ftn.xws.bo.mt900.Mt900 handleMt103(
        @WebParam(partName = "mt103", name = "mt103", targetNamespace = "http://www.ftn.uns.ac.rs/xws/bo/mt103")
        rs.ac.uns.ftn.xws.bo.mt103.Mt103 mt103
    );
}
